##
## Build
##

FROM golang:1.19-buster as builder

WORKDIR /go/src/github.com/turbo-d/stream-player/server

COPY go.* ./
RUN go mod download

COPY . ./

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o build/stream-player/server github.com/turbo-d/stream-player/server

##
## Deploy
##

FROM alpine

RUN apk add --no-cache ca-certificates && update-ca-certificates

WORKDIR /usr/bin/stream-player

COPY --from=builder /go/src/github.com/turbo-d/stream-player/server/build/stream-player/server ./

EXPOSE 8080 8080

ENTRYPOINT ["./server"]